// Textos das telas do hóspede em português (do Brasil — a língua dos
// hóspedes, como pede a marca), espanhol e inglês. Complementa
// translations.js (que tem os textos da lista/busca). Chaves 'd:…' traduzem
// valores que vêm dos dados em português (piso, vista, camas, comodidades).
import { money, parseYMD } from './helpers.js';

const s = (n, um, varios) => (n === 1 ? um : varios);
const dataEm = (locale) => (d) => (d ? parseYMD(d).toLocaleDateString(locale, { day: '2-digit', month: 'long', year: 'numeric' }) : '');

const pt = {
  noites: (n) => `${n} ${s(n, 'noite', 'noites')}`,
  pessoas: (n) => `${n} ${s(n, 'pessoa', 'pessoas')}`,
  fim_de_semana: 'fim de semana',
  taxa_obrigatoria: 'Obrigatória', taxa_opcional: 'Opcional',
  m_menos_pessoa: 'Menos uma pessoa', m_mais_pessoa: 'Mais uma pessoa',

  /* reserva */
  bk_titulo_resumo: 'Confira sua estadia', bk_escolher_datas: 'Escolher datas',
  bk_sem_datas: 'Escolha as datas de entrada e saída para ver o preço.',
  bk_continuar: 'Continuar', bk_datas: 'Datas', bk_alterar: 'Alterar', bk_pessoas: 'Pessoas',
  bk_maximo: (n) => `máximo ${n}`,
  bk_menos_pessoa: 'Menos uma pessoa', bk_mais_pessoa: 'Mais uma pessoa',
  bk_menos_pessoa_em: (a) => `Menos uma pessoa no ${a}`, bk_mais_pessoa_em: (a) => `Mais uma pessoa no ${a}`,
  bk_pessoas_por_apto: 'Pessoas por apartamento',
  bk_total_combinado: 'Preço total combinado', bk_total: 'Preço total',
  bk_sinal_para_reservar: (p) => `Sinal para reservar (${p}%)`,
  bk_restante: 'Restante (no check-in)',
  bk_nada_cobrado: 'Nada é cobrado até você confirmar no último passo.',
  bk_titulo_extras: 'Serviços extras', bk_sub_extras: 'Adicione serviços à sua estadia (opcional)',
  bk_por_reserva: 'por reserva', bk_por_noite: 'por noite', bk_por_hospede: 'por pessoa',
  bk_escopo_grupo: 'Para o grupo (1×)', bk_escopo_apto: 'Por apartamento (2×)',
  bk_menos_extra: (n) => `Diminuir ${n}`, bk_mais_extra: (n) => `Aumentar ${n}`,
  bk_extras_total: 'Extras',
  bk_titulo_dados: 'Seus dados', bk_nome: 'Nome completo', bk_nome_ph: 'Como no documento',
  bk_email: 'E-mail', bk_telefone: 'Telefone (WhatsApp)',
  bk_erro_nome: 'Escreva seu nome completo.',
  bk_erro_email: 'Confira o e-mail — parece incompleto.',
  bk_erro_telefone: 'Confira o telefone, com DDD.',
  bk_privacidade: 'Usamos estes dados só para a sua reserva: enviar a confirmação e falar com você sobre a estadia.',
  bk_titulo_revisao: 'Revisar e confirmar', bk_processando: 'Processando…', bk_confirmar: 'Confirmar reserva',
  bk_ocultar: 'Ocultar', bk_detalhes: 'Detalhes',
  bk_sinal_agora: (p) => `Sinal a pagar agora (${p}%)`,
  bk_cancelamento_resumo: 'As condições variam com a antecedência do check-in.',
  bk_ver_politica: 'Ver política completa', bk_escolher_outras_datas: 'Escolher outras datas',
  bk_falar_whatsapp: 'Falar conosco pelo WhatsApp',
  bk_duas_reservas: 'Serão feitas 2 reservas ligadas, no mesmo nome e com um só pagamento.',
  bk_sinal_confirma: 'O pagamento do sinal confirma a reserva.',

  /* erros ao reservar (vêm do servidor) */
  err_indisponivel: 'Estas datas acabaram de ser reservadas por outra pessoa. Escolha outras datas.',
  err_preco_mudou: (e) => `Os valores foram atualizados enquanto você reservava: total de ${money(e?.total)}, sinal de ${money(e?.sinal)}. Confira os valores acima e confirme de novo.`,
  err_muitas_pendentes: 'Você já tem reservas aguardando o pagamento do sinal. Conclua o pagamento delas ou fale conosco pelo WhatsApp.',
  err_minimo_noites: (e) => `Para estas datas a estadia mínima é de ${e?.min} noites.`,
  err_maximo_noites: (e) => `Para estas datas a estadia máxima é de ${e?.max} noites.`,
  err_capacidade: 'O número de pessoas passa da capacidade do apartamento.',
  err_datas: 'As datas escolhidas não podem ser reservadas. Escolha outras datas.',
  err_datas_fechadas: (e) => `Ainda não abrimos reservas para essas datas (por enquanto, até ${dataEm('pt-BR')(e?.ate)}).`,
  err_estadia_longa: (e) => `Pelo site, estadias de até ${e?.max} noites. Para mais tempo, fale conosco.`,
  err_generico: 'Não conseguimos concluir agora. Tente de novo em instantes ou fale conosco pelo WhatsApp.',

  /* confirmação */
  cf_titulo_falhou: 'Pagamento não concluído', cf_titulo_paga: 'Reserva confirmada',
  cf_titulo_aguardando: 'Pagamento em análise', cf_titulo_recebida: 'Reserva recebida',
  cf_nova_pesquisa: 'Fazer nova pesquisa',
  cf_generico: 'Recebemos o retorno do pagamento. A confirmação com todos os detalhes chega no seu e-mail.',
  cf_generico_falhou: 'O pagamento não foi concluído. Se quiser, fale conosco pelo WhatsApp para tentar de novo ou combinar outra forma de pagamento.',
  cf_seu_codigo: 'Seu código de reserva', cf_apartamento: 'Apartamento', cf_apartamentos: 'Apartamentos',
  cf_estadia: 'Estadia', cf_hospede: 'Hóspede',
  cf_sinal_pago: (p) => `Sinal pago (${p}%)`, cf_sinal_a_pagar: (p) => `Sinal a pagar (${p}%)`,
  cf_texto_falhou: 'O pagamento do sinal não foi concluído e a reserva ainda não está garantida. Fale conosco pelo WhatsApp para tentar de novo ou combinar outra forma de pagamento.',
  cf_texto_pago: (e) => `Seu apartamento está reservado. Enviamos os detalhes para ${e}. O saldo é pago no check-in.`,
  cf_texto_aguardando: (e) => `Recebemos seu pagamento e estamos aguardando a confirmação (no Pix pode levar alguns minutos). Os detalhes vão para ${e}.`,
  cf_texto_manual: (e) => `Recebemos sua reserva. Para garanti-la, falta o pagamento do sinal: vamos entrar em contato pelo WhatsApp ou pelo e-mail ${e} com as instruções.`,

  /* site: lista, busca, topo e rodapé */
  ps_favoritar: (n) => `Salvar ${n}`, ps_desfavoritar: (n) => `Tirar ${n} dos salvos`,
  ps_indisponivel: 'Indisponível', ps_ver_datas_livres: 'Ver datas livres',
  ps_ate_pessoas: (n) => `até ${n} pessoas`,
  ps_combinar_obrigatorio: (h) => `Combine com outro apartamento — necessário para ${h} pessoas`,
  ps_combinar: 'Pode combinar com outro apartamento',
  ps_total: 'total', ps_taxas_incluidas: 'taxas incluídas', ps_datas_para_preco: 'Escolha as datas para ver o preço total, com taxas',
  ps_disp_no: (n) => `Disponibilidade no ${n} para estas datas.`,
  ps_disp_nos: (k) => (k === 2 ? 'Disponibilidade nos dois residenciais para estas datas.' : `Disponibilidade nos ${k} residenciais para estas datas.`),
  ps_disp: 'Disponibilidade para estas datas.',
  ps_n_de_m_disponiveis: (a, t) => `${a} de ${t} ${s(t, 'apartamento', 'apartamentos')} ${s(a, 'disponível', 'disponíveis')}`,
  ps_n_apartamentos: (t) => `${t} ${s(t, 'apartamento', 'apartamentos')}`,
  ps_n_casas: (t) => `${t} ${s(t, 'casa', 'casas')}`,
  ps_n_aptos_casas: (a, c) => `${a} ${s(a, 'apartamento', 'apartamentos')} e ${c} ${s(c, 'casa', 'casas')}`,
  ps_n_de_m_disponiveis_curto: (a, t) => `${a} de ${t} ${s(a, 'disponível', 'disponíveis')}`,
  ps_combo_titulo: (h, n) => `Para ${h} pessoas no ${n} é preciso combinar apartamentos.`,
  ps_combo_sugestao: 'Sugestão:', ps_combo_capacidade: (c) => `capacidade total de ${c} pessoas.`,
  ps_combo_tres: 'Pelo site dá para reservar até 2 apartamentos juntos; para 3 ou mais, fale conosco pelo WhatsApp.',
  ps_combo_sem: 'Não há apartamentos livres suficientes neste residencial para estas datas.',
  ps_ver_apto: (n) => `Ver ${n}`,
  ps_selecionar_entrada: 'Escolher entrada', ps_selecionar_saida: 'Escolher saída',
  ps_limpar_consulta: 'Limpar pesquisa',
  ps_limpar_filtro: 'Limpar filtro', ps_filtros: 'Filtros',
  ps_hero_local: 'Praia da Pinheira · Palhoça · Santa Catarina',
  ps_hero_titulo_1: 'A sua casa de verão,', ps_hero_titulo_2: 'perto do mar.',
  ps_hero_texto: (n) => `Apartamentos mobiliados e completos em ${n} residenciais do Grupo PinheiraMar. Escolha as datas e veja o que está livre.`,
  ps_ver_apartamentos: 'Ver apartamentos', ps_ordenar: 'Ordenar por',
  ps_ordem_recomendados: 'Recomendados', ps_ordem_menor: 'Preço: menor primeiro', ps_ordem_maior: 'Preço: maior primeiro',
  ps_essencia: 'A sua casa de verão.', ps_horarios: 'Horários',
  ps_checkin_a_partir: (h) => `Check-in a partir das ${h}`, ps_checkout_ate: (h) => `Check-out até ${h}`,
  ps_como_chegar: 'Como chegar', ps_km_floripa: '55 km de Florianópolis', ps_km_aeroporto: '66 km do aeroporto',
  ps_datas_livres: (n) => `Datas livres · ${n}`,
  ps_datas_livres_sub: 'Escolha um período livre para ver este apartamento nos resultados.',

  /* página do apartamento */
  ap_voltar: 'Voltar', ap_link_copiado: 'Link copiado', ap_compartilhar: 'Compartilhar', ap_salvar: 'Salvar', ap_salvo: 'Salvo',
  ap_resumo: (cap, q, c) => `Até ${cap} pessoas · ${q} ${s(q, 'quarto', 'quartos')} · ${c} ${s(c, 'cama', 'camas')}`,
  ap_ver_avaliacoes: 'Ver avaliações no Google', ap_avaliacoes_google: (n) => `${n} avaliações no Google`, ap_n_avaliacoes: (n) => `${n} avaliações`,
  ap_frente_mar: 'Frente Mar', ap_foto_n: (i, n) => `${n} — foto ${i}`, ap_ver_todas_fotos: (n) => `Ver as ${n} fotos`,
  ap_fechar: 'Fechar', ap_foto_anterior: 'Foto anterior', ap_proxima_foto: 'Próxima foto',
  ap_pontos_fortes: 'Pontos fortes do apartamento',
  ap_hl_wifi: 'Wi-Fi grátis', ap_hl_estacionamento: 'Estacionamento', ap_hl_vista_mar: 'Vista para o mar', ap_hl_churrasqueira: 'Churrasqueira',
  ap_hl_ar: 'Ar-condicionado', ap_hl_cozinha: 'Cozinha equipada', ap_hl_piscina: 'Piscina', ap_hl_varanda: 'Varanda',
  ap_sobre: 'Sobre o apartamento', ap_acomodacoes: 'Onde dormir', ap_comodidades: 'Comodidades', ap_capacidade: 'Capacidade',
  ap_capacidade_maxima: 'capacidade máxima', ap_quartos: (n) => `${n} ${s(n, 'quarto', 'quartos')}`, ap_para_dormir: 'para dormir', ap_area: 'área do apartamento',
  ap_regras: 'Regras da casa',
  ap_regra_checkin: 'Check-in', ap_regra_checkin_txt: (h) => `A partir das ${h}`,
  ap_regra_checkout: 'Check-out', ap_regra_checkout_txt: (h) => `Até ${h}`,
  ap_regra_silencio: 'Horário de silêncio', ap_regra_silencio_txt: 'Para o descanso de todos, silêncio das 22h às 7h (exceto no Réveillon e no Carnaval).',
  ap_regra_pets: 'Animais de estimação', ap_regra_pets_txt: (p) => `Bem-vindos, com taxa única de ${p} por animal (até 10 kg, no máximo 2).`,
  ap_regra_pets_consulte: 'Fale conosco antes de trazer animais.',
  ap_regra_estacionamento: 'Estacionamento', ap_regra_vaga_obrig: 'Vaga de garagem mediante taxa única obrigatória.',
  ap_regra_vaga: 'Consulte a disponibilidade de vaga.', ap_regra_vaga_extra: (p) => `Vaga adicional: ${p} (sujeita a disponibilidade).`,
  ap_regra_fumar: 'Fumar', ap_regra_fumar_txt: 'Não é permitido fumar nas áreas internas e comuns.',
  ap_localizacao: 'Localização', ap_mapa: 'Mapa', ap_comercio: 'A poucos passos do comércio local: supermercados, bares e restaurantes.',
  ap_datas_e_reserva: 'Datas e reserva', ap_sem_datas: 'Sem datas', ap_limpar_pesquisa: 'Limpar pesquisa',
  ap_checkin: 'Check-in', ap_checkout: 'Check-out', ap_adicionar_data: 'Escolher data', ap_hospedes: 'Pessoas',
  ap_precisa_segundo: (h, cap) => `Você procurou para ${h} pessoas e este apartamento leva até ${cap}. Marque "Adicionar segundo apartamento" abaixo para reservar para todo o grupo.`,
  ap_segundo_apto: 'Adicionar segundo apartamento', ap_segundo_apto_sub: 'Reserva conjunta · mesmo nome · um só pagamento',
  ap_escolha_segundo: '— Escolha o 2º apartamento —', ap_indisponivel_curto: 'indisponível', ap_pessoas_em: (n) => `Pessoas no ${n}`,
  ap_minimo_noites: (n, t) => `Para estas datas${t ? ` (${t})` : ''}, a estadia mínima é de ${n} noites.`,
  ap_maximo_noites: (n, t) => `Para estas datas${t ? ` (${t})` : ''}, a estadia máxima é de ${n} noites.`,
  ap_disponivel: 'Disponível', ap_indisponivel_datas: 'Indisponível nestas datas', ap_sinal: (p) => `Sinal (${p}%)`,
  ap_btn_selecione_datas: 'Escolha as datas', ap_btn_indisponivel: 'Indisponível',
  ap_btn_minimo: (n) => `Mínimo de ${n} noites`, ap_btn_maximo: (n) => `Máximo de ${n} noites`,
  ap_btn_adicione_segundo: 'Adicione o 2º apartamento', ap_btn_escolha_segundo: 'Escolha o 2º apartamento',
  ap_btn_segundo_indisponivel: (n) => `${n} indisponível`, ap_btn_capacidade: (h) => `Capacidade insuficiente para ${h} pessoas`,
  ap_btn_reservar: 'Reservar agora', ap_sem_cobrancas: (p) => `Nada é cobrado até você confirmar · ${p}% de sinal para reservar`,
  ap_precisa_ajuda: 'Precisa de ajuda?', ap_fale_whatsapp: 'Fale conosco no WhatsApp',
  ap_ver_detalhes_preco: 'Ver detalhes do preço', ap_reservar_curto: 'Reservar', ap_ocupado_datas: 'Ocupado nestas datas',
  ap_mudar_datas: 'Mudar datas', ap_falta_detalhe: 'Falta um detalhe para reservar',
  ap_adicione_datas_preco: 'Adicione as datas para ver o preço no período que deseja', ap_escolher_datas: 'Escolher datas',

  /* calendário */
  cal_mes_anterior: 'Mês anterior', cal_proximo_mes: 'Próximo mês',
  cal_escolha_saida: 'Escolha a data de saída', cal_escolha_entrada: 'Escolha a data de entrada',
  cal_ocupado: 'ocupado', cal_fechado: 'reservas ainda não abertas', cal_abertas_ate: (d) => `Reservas abertas até ${d}.`,
  cal_desmarcar: 'Desmarcar datas', cal_legenda_livre: 'livre', cal_legenda_ocupado: 'ocupado',

  /* Conheça a Pinheira */
  ds_tab_pinheira: 'A Pinheira', ds_tab_atrativos: 'Atrativos', ds_tab_chegar: 'Como chegar',
  ds_titulo: 'Conheça a Pinheira',
  ds_sub: 'Uma das praias mais procuradas da região de Florianópolis: tradição açoriana, piscinas naturais e o melhor do litoral catarinense.',
  ds_viva: 'O lugar faz parte das férias',
  ds_p1: 'A Praia da Pinheira é uma das praias mais frequentadas da Grande Florianópolis e recebe visitantes de todo o Brasil e do exterior.',
  ds_p2: 'Fica numa enseada a 37 km do centro de Palhoça e a 55 km do centro de Florianópolis, e se divide em duas praias: a Praia de Baixo e a Praia de Cima, uma de frente para a outra.',
  ds_p3: 'A Pinheira já não é só um povoado de pescadores de tradição açoriana — o desenvolvimento chegou, mas a convivência tranquila entre visitantes e moradores continua, e os ranchos de pesca ainda marcam a paisagem.',
  ds_origem: 'A origem do nome',
  ds_origem_txt: 'Conta-se que havia na enseada árvores de madeira leve e resistente, muito usadas para fazer boias para as redes de pesca. O fruto parecia uma pinha — por isso as árvores eram chamadas de pinheiras, e a praia, que ainda não tinha nome, ficou sendo a Pinheira.',
  ds_por_que: 'Por que escolher a Pinheira?',
  ds_motivo_1: 'Praia de Baixo: águas calmas, ótima para famílias',
  ds_motivo_2: 'Pesca artesanal e peixe fresco todos os dias',
  ds_motivo_3: 'Pôr do sol sobre o Pontão e as pedras',
  ds_motivo_4: 'Praias vizinhas para todos os gostos — surfe, mergulho e trilhas',
  ds_motivo_5: 'Comunidade acolhedora e ambiente tranquilo para as crianças',
  ds_motivo_6: 'A 3 km da famosa Guarda do Embaú',
  ds_atrativos_titulo: 'Atrativos e passeios',
  ds_atrativos_sub: 'A Enseada da Pinheira tem de tudo — da praia deserta para surfistas ao passeio de barco para a família, a poucos minutos dos residenciais.',
  ds_mapa_enseada: 'Mapa da Enseada da Pinheira', ds_enseada: 'Enseada da Pinheira — Palhoça, Santa Catarina', ds_destaque: 'destaque',
  ds_at_pontao: 'Pontão da Pinheira',
  ds_at_pontao_txt: 'Conjunto de rochas entre a praia e o costão, com piscinas naturais formadas pelas marés. Ótimo para banho de mar, pesca artesanal e para ver o pôr do sol.',
  ds_at_baixo: 'Praia de Baixo',
  ds_at_baixo_txt: 'Praia de enseada com 7 km de extensão, de águas calmas e limpas. Perfeita para famílias, caminhadas e esportes náuticos — e com peixe fresco da pesca artesanal todos os dias.',
  ds_at_urubu: 'Pedra do Urubu',
  ds_at_urubu_txt: 'Uma das vistas mais bonitas de Santa Catarina: lá de cima se vê a enseada da Pinheira, a Praia do Sonho, a Ponta dos Papagaios e a foz do Rio da Madre. Vale cada passo da subida.',
  ds_at_cima: 'Praia de Cima',
  ds_at_cima_txt: 'Águas limpas e muito movimento no verão, com posto de salva-vidas, bares, lojas e restaurantes.',
  ds_at_prainha: 'Prainha',
  ds_at_prainha_txt: 'Praia deserta, com ondas fortes para surfistas. Mar agitado, mas de água cristalina e paisagem selvagem.',
  ds_at_guarda: 'Guarda do Embaú',
  ds_at_guarda_txt: 'A 3 km da Pinheira, na foz do Rio da Madre, com mar aberto e vista para a Ilha do Coral. Conhecida em todo o Brasil — um lugar de paz e beleza.',
  ds_at_maco: 'Praia do Maço',
  ds_at_maco_txt: 'Praia deserta de águas limpas e ondas fortes, com acesso por três trilhas que saem do pé do morro da Pinheira. Para quem procura natureza e sossego.',
  ds_at_tabuleiro: 'Parque da Serra do Tabuleiro',
  ds_at_tabuleiro_txt: 'Com guias, dá para fazer trilhas e ver animais e plantas nativos. Um dos maiores parques de preservação contínua do Brasil.',
  ds_chegar_titulo: 'Como chegar à Pinheira',
  ds_aviao: 'De avião', ds_aviao_txt: 'Aeroporto Internacional Hercílio Luz (Florianópolis), a 66 km (cerca de 1 hora de carro). Recomendamos alugar um carro ou contratar um transfer.',
  ds_carro: 'De carro', ds_carro_txt: 'BR-101 Sul até Palhoça e depois o acesso à Praia da Pinheira. Estacionamento mediante taxa obrigatória (1 vaga por apartamento); vaga adicional com acréscimo.',
  ds_onibus: 'De ônibus', ds_onibus_txt: 'Rodoviária de Florianópolis → linha para Palhoça → van ou mototáxi até a Pinheira. Cerca de 1h30 no total.',
  ds_distancias: 'Distâncias úteis', ds_distancias_txt: 'Centro de Florianópolis: 55 km · Palhoça (centro): 37 km · Guarda do Embaú: 3 km · Garopaba: 33 km · Imbituba: 53 km.',
  ds_rota: 'Ver rota',
};

const es = {
  noites: (n) => `${n} ${s(n, 'noche', 'noches')}`,
  pessoas: (n) => `${n} ${s(n, 'persona', 'personas')}`,
  fim_de_semana: 'fin de semana',
  taxa_obrigatoria: 'Obligatoria', taxa_opcional: 'Opcional',
  m_menos_pessoa: 'Una persona menos', m_mais_pessoa: 'Una persona más',

  bk_titulo_resumo: 'Revise su estadía', bk_escolher_datas: 'Elegir fechas',
  bk_sem_datas: 'Elija las fechas de entrada y salida para ver el precio.',
  bk_continuar: 'Continuar', bk_datas: 'Fechas', bk_alterar: 'Cambiar', bk_pessoas: 'Personas',
  bk_maximo: (n) => `máximo ${n}`,
  bk_menos_pessoa: 'Una persona menos', bk_mais_pessoa: 'Una persona más',
  bk_menos_pessoa_em: (a) => `Una persona menos en ${a}`, bk_mais_pessoa_em: (a) => `Una persona más en ${a}`,
  bk_pessoas_por_apto: 'Personas por departamento',
  bk_total_combinado: 'Precio total combinado', bk_total: 'Precio total',
  bk_sinal_para_reservar: (p) => `Seña para reservar (${p}%)`,
  bk_restante: 'Resto (en el check-in)',
  bk_nada_cobrado: 'No se cobra nada hasta que confirme en el último paso.',
  bk_titulo_extras: 'Servicios extra', bk_sub_extras: 'Agregue servicios a su estadía (opcional)',
  bk_por_reserva: 'por reserva', bk_por_noite: 'por noche', bk_por_hospede: 'por persona',
  bk_escopo_grupo: 'Para el grupo (1×)', bk_escopo_apto: 'Por departamento (2×)',
  bk_menos_extra: (n) => `Disminuir ${n}`, bk_mais_extra: (n) => `Aumentar ${n}`,
  bk_extras_total: 'Extras',
  bk_titulo_dados: 'Sus datos', bk_nome: 'Nombre completo', bk_nome_ph: 'Como en el documento',
  bk_email: 'E-mail', bk_telefone: 'Teléfono (WhatsApp)',
  bk_erro_nome: 'Escriba su nombre completo.',
  bk_erro_email: 'Revise el e-mail: parece incompleto.',
  bk_erro_telefone: 'Revise el teléfono, con código de área.',
  bk_privacidade: 'Usamos estos datos solo para su reserva: enviarle la confirmación y contactarlo sobre la estadía.',
  bk_titulo_revisao: 'Revisar y confirmar', bk_processando: 'Procesando…', bk_confirmar: 'Confirmar reserva',
  bk_ocultar: 'Ocultar', bk_detalhes: 'Detalles',
  bk_sinal_agora: (p) => `Seña a pagar ahora (${p}%)`,
  bk_cancelamento_resumo: 'Las condiciones dependen de la anticipación con que cancele.',
  bk_ver_politica: 'Ver la política completa', bk_escolher_outras_datas: 'Elegir otras fechas',
  bk_falar_whatsapp: 'Hablar con nosotros por WhatsApp',
  bk_duas_reservas: 'Se harán 2 reservas vinculadas, al mismo nombre y con un solo pago.',
  bk_sinal_confirma: 'El pago de la seña confirma la reserva.',

  err_indisponivel: 'Otra persona acaba de reservar estas fechas. Elija otras fechas.',
  err_preco_mudou: (e) => `Los valores se actualizaron mientras reservaba: total de ${money(e?.total)}, seña de ${money(e?.sinal)}. Revise los valores y confirme de nuevo.`,
  err_muitas_pendentes: 'Ya tiene reservas esperando el pago de la seña. Complete esos pagos o contáctenos por WhatsApp.',
  err_minimo_noites: (e) => `Para estas fechas la estadía mínima es de ${e?.min} noches.`,
  err_maximo_noites: (e) => `Para estas fechas la estadía máxima es de ${e?.max} noches.`,
  err_capacidade: 'La cantidad de personas supera la capacidad del departamento.',
  err_datas: 'Las fechas elegidas no se pueden reservar. Elija otras fechas.',
  err_datas_fechadas: (e) => `Todavía no abrimos reservas para esas fechas (por ahora, hasta el ${dataEm('es-AR')(e?.ate)}).`,
  err_estadia_longa: (e) => `Por el sitio, estadías de hasta ${e?.max} noches. Para más tiempo, contáctenos.`,
  err_generico: 'No pudimos completar la reserva ahora. Intente de nuevo en unos instantes o contáctenos por WhatsApp.',

  cf_titulo_falhou: 'Pago no completado', cf_titulo_paga: 'Reserva confirmada',
  cf_titulo_aguardando: 'Pago en proceso', cf_titulo_recebida: 'Reserva recibida',
  cf_nova_pesquisa: 'Hacer una nueva búsqueda',
  cf_generico: 'Recibimos la respuesta del pago. La confirmación con todos los detalles llegará a su e-mail.',
  cf_generico_falhou: 'El pago no se completó. Si quiere, escríbanos por WhatsApp para intentar de nuevo o acordar otra forma de pago.',
  cf_seu_codigo: 'Su código de reserva', cf_apartamento: 'Departamento', cf_apartamentos: 'Departamentos',
  cf_estadia: 'Estadía', cf_hospede: 'Huésped',
  cf_sinal_pago: (p) => `Seña pagada (${p}%)`, cf_sinal_a_pagar: (p) => `Seña a pagar (${p}%)`,
  cf_texto_falhou: 'El pago de la seña no se completó y la reserva todavía no está garantizada. Escríbanos por WhatsApp para intentar de nuevo o acordar otra forma de pago.',
  cf_texto_pago: (e) => `Su departamento está reservado. Enviamos los detalles a ${e}. El saldo se paga en el check-in.`,
  cf_texto_aguardando: (e) => `Recibimos su pago y estamos esperando la confirmación (con Pix puede tardar unos minutos). Los detalles irán a ${e}.`,
  cf_texto_manual: (e) => `Recibimos su reserva. Para garantizarla, falta el pago de la seña: nos comunicaremos por WhatsApp o por e-mail (${e}) con las instrucciones.`,

  ps_favoritar: (n) => `Guardar ${n}`, ps_desfavoritar: (n) => `Quitar ${n} de guardados`,
  ps_indisponivel: 'No disponible', ps_ver_datas_livres: 'Ver fechas libres',
  ps_ate_pessoas: (n) => `hasta ${n} personas`,
  ps_combinar_obrigatorio: (h) => `Combine con otro departamento: necesario para ${h} personas`,
  ps_combinar: 'Se puede combinar con otro departamento',
  ps_total: 'total', ps_taxas_incluidas: 'tasas incluidas', ps_datas_para_preco: 'Elija las fechas para ver el precio total, con tasas',
  ps_disp_no: (n) => `Disponibilidad en ${n} para estas fechas.`,
  ps_disp_nos: (k) => (k === 2 ? 'Disponibilidad en los dos residenciales para estas fechas.' : `Disponibilidad en los ${k} residenciales para estas fechas.`),
  ps_disp: 'Disponibilidad para estas fechas.',
  ps_n_de_m_disponiveis: (a, t) => `${a} de ${t} ${s(t, 'departamento', 'departamentos')} ${s(a, 'disponible', 'disponibles')}`,
  ps_n_apartamentos: (t) => `${t} ${s(t, 'departamento', 'departamentos')}`,
  ps_n_casas: (t) => `${t} ${s(t, 'casa', 'casas')}`,
  ps_n_aptos_casas: (a, c) => `${a} ${s(a, 'departamento', 'departamentos')} y ${c} ${s(c, 'casa', 'casas')}`,
  ps_n_de_m_disponiveis_curto: (a, t) => `${a} de ${t} ${s(a, 'disponible', 'disponibles')}`,
  ps_combo_titulo: (h, n) => `Para ${h} personas en ${n} hay que combinar departamentos.`,
  ps_combo_sugestao: 'Sugerencia:', ps_combo_capacidade: (c) => `capacidad total de ${c} personas.`,
  ps_combo_tres: 'Por el sitio se pueden reservar hasta 2 departamentos juntos; para 3 o más, escríbanos por WhatsApp.',
  ps_combo_sem: 'No hay suficientes departamentos libres en este residencial para estas fechas.',
  ps_ver_apto: (n) => `Ver ${n}`,
  ps_selecionar_entrada: 'Elegir entrada', ps_selecionar_saida: 'Elegir salida',
  ps_limpar_consulta: 'Borrar búsqueda',
  ps_limpar_filtro: 'Quitar filtro', ps_filtros: 'Filtros',
  ps_hero_local: 'Praia da Pinheira · Palhoça · Santa Catarina',
  ps_hero_titulo_1: 'Su casa de verano,', ps_hero_titulo_2: 'cerca del mar.',
  ps_hero_texto: (n) => `Departamentos amueblados y completos en ${n} residenciales del Grupo PinheiraMar. Elija las fechas y vea qué está libre.`,
  ps_ver_apartamentos: 'Ver departamentos', ps_ordenar: 'Ordenar por',
  ps_ordem_recomendados: 'Recomendados', ps_ordem_menor: 'Precio: menor primero', ps_ordem_maior: 'Precio: mayor primero',
  ps_essencia: 'Su casa de verano.', ps_horarios: 'Horarios',
  ps_checkin_a_partir: (h) => `Check-in desde las ${h}`, ps_checkout_ate: (h) => `Check-out hasta las ${h}`,
  ps_como_chegar: 'Cómo llegar', ps_km_floripa: 'A 55 km de Florianópolis', ps_km_aeroporto: 'A 66 km del aeropuerto',
  ps_datas_livres: (n) => `Fechas libres · ${n}`,
  ps_datas_livres_sub: 'Elija un período libre para ver este departamento en los resultados.',

  ap_voltar: 'Volver', ap_link_copiado: 'Enlace copiado', ap_compartilhar: 'Compartir', ap_salvar: 'Guardar', ap_salvo: 'Guardado',
  ap_resumo: (cap, q, c) => `Hasta ${cap} personas · ${q} ${s(q, 'dormitorio', 'dormitorios')} · ${c} ${s(c, 'cama', 'camas')}`,
  ap_ver_avaliacoes: 'Ver opiniones en Google', ap_avaliacoes_google: (n) => `${n} opiniones en Google`, ap_n_avaliacoes: (n) => `${n} opiniones`,
  ap_frente_mar: 'Frente al mar', ap_foto_n: (i, n) => `${n} — foto ${i}`, ap_ver_todas_fotos: (n) => `Ver las ${n} fotos`,
  ap_fechar: 'Cerrar', ap_foto_anterior: 'Foto anterior', ap_proxima_foto: 'Foto siguiente',
  ap_pontos_fortes: 'Lo mejor del departamento',
  ap_hl_wifi: 'Wi-Fi gratis', ap_hl_estacionamento: 'Estacionamiento', ap_hl_vista_mar: 'Vista al mar', ap_hl_churrasqueira: 'Parrilla',
  ap_hl_ar: 'Aire acondicionado', ap_hl_cozinha: 'Cocina equipada', ap_hl_piscina: 'Pileta', ap_hl_varanda: 'Balcón',
  ap_sobre: 'Sobre el departamento', ap_acomodacoes: 'Dónde dormir', ap_comodidades: 'Comodidades', ap_capacidade: 'Capacidad',
  ap_capacidade_maxima: 'capacidad máxima', ap_quartos: (n) => `${n} ${s(n, 'dormitorio', 'dormitorios')}`, ap_para_dormir: 'para dormir', ap_area: 'superficie del departamento',
  ap_regras: 'Normas de la casa',
  ap_regra_checkin: 'Check-in', ap_regra_checkin_txt: (h) => `Desde las ${h}`,
  ap_regra_checkout: 'Check-out', ap_regra_checkout_txt: (h) => `Hasta las ${h}`,
  ap_regra_silencio: 'Horario de silencio', ap_regra_silencio_txt: 'Para el descanso de todos, silencio de 22 a 7 h (excepto en Año Nuevo y Carnaval).',
  ap_regra_pets: 'Mascotas', ap_regra_pets_txt: (p) => `Bienvenidas, con una tasa única de ${p} por mascota (hasta 10 kg, máximo 2).`,
  ap_regra_pets_consulte: 'Consúltenos antes de traer mascotas.',
  ap_regra_estacionamento: 'Estacionamiento', ap_regra_vaga_obrig: 'Cochera con tasa única obligatoria.',
  ap_regra_vaga: 'Consulte la disponibilidad de cochera.', ap_regra_vaga_extra: (p) => `Cochera adicional: ${p} (sujeta a disponibilidad).`,
  ap_regra_fumar: 'Fumar', ap_regra_fumar_txt: 'No se permite fumar en las áreas internas ni comunes.',
  ap_localizacao: 'Ubicación', ap_mapa: 'Mapa', ap_comercio: 'A pocos pasos del comercio local: supermercados, bares y restaurantes.',
  ap_datas_e_reserva: 'Fechas y reserva', ap_sem_datas: 'Sin fechas', ap_limpar_pesquisa: 'Borrar búsqueda',
  ap_checkin: 'Check-in', ap_checkout: 'Check-out', ap_adicionar_data: 'Elegir fecha', ap_hospedes: 'Personas',
  ap_precisa_segundo: (h, cap) => `Buscó para ${h} personas y este departamento admite hasta ${cap}. Marque "Agregar un segundo departamento" para reservar para todo el grupo.`,
  ap_segundo_apto: 'Agregar un segundo departamento', ap_segundo_apto_sub: 'Reserva conjunta · mismo nombre · un solo pago',
  ap_escolha_segundo: '— Elija el 2.º departamento —', ap_indisponivel_curto: 'no disponible', ap_pessoas_em: (n) => `Personas en ${n}`,
  ap_minimo_noites: (n, t) => `Para estas fechas${t ? ` (${t})` : ''}, la estadía mínima es de ${n} noches.`,
  ap_maximo_noites: (n, t) => `Para estas fechas${t ? ` (${t})` : ''}, la estadía máxima es de ${n} noches.`,
  ap_disponivel: 'Disponible', ap_indisponivel_datas: 'No disponible en estas fechas', ap_sinal: (p) => `Seña (${p}%)`,
  ap_btn_selecione_datas: 'Elija las fechas', ap_btn_indisponivel: 'No disponible',
  ap_btn_minimo: (n) => `Mínimo ${n} noches`, ap_btn_maximo: (n) => `Máximo ${n} noches`,
  ap_btn_adicione_segundo: 'Agregue el 2.º departamento', ap_btn_escolha_segundo: 'Elija el 2.º departamento',
  ap_btn_segundo_indisponivel: (n) => `${n} no disponible`, ap_btn_capacidade: (h) => `Capacidad insuficiente para ${h} personas`,
  ap_btn_reservar: 'Reservar ahora', ap_sem_cobrancas: (p) => `No se cobra nada hasta confirmar · ${p}% de seña para reservar`,
  ap_precisa_ajuda: '¿Necesita ayuda?', ap_fale_whatsapp: 'Escríbanos por WhatsApp',
  ap_ver_detalhes_preco: 'Ver el detalle del precio', ap_reservar_curto: 'Reservar', ap_ocupado_datas: 'Ocupado en estas fechas',
  ap_mudar_datas: 'Cambiar fechas', ap_falta_detalhe: 'Falta un detalle para reservar',
  ap_adicione_datas_preco: 'Añada las fechas para ver el precio en el período que desea', ap_escolher_datas: 'Elegir fechas',

  cal_mes_anterior: 'Mes anterior', cal_proximo_mes: 'Mes siguiente',
  cal_escolha_saida: 'Elija la fecha de salida', cal_escolha_entrada: 'Elija la fecha de entrada',
  cal_ocupado: 'ocupado', cal_fechado: 'reservas aún no abiertas', cal_abertas_ate: (d) => `Reservas abiertas hasta el ${d}.`,
  cal_desmarcar: 'Borrar fechas', cal_legenda_livre: 'libre', cal_legenda_ocupado: 'ocupado',

  ds_tab_pinheira: 'La Pinheira', ds_tab_atrativos: 'Atractivos', ds_tab_chegar: 'Cómo llegar',
  ds_titulo: 'Conozca la Pinheira',
  ds_sub: 'Una de las playas más buscadas de la región de Florianópolis: tradición azoriana, piletas naturales y lo mejor del litoral de Santa Catarina.',
  ds_viva: 'El lugar es parte de las vacaciones',
  ds_p1: 'La Praia da Pinheira es una de las playas más concurridas de la Gran Florianópolis y recibe visitantes de todo Brasil y del exterior.',
  ds_p2: 'Está en una ensenada a 37 km del centro de Palhoça y a 55 km del centro de Florianópolis, y se divide en dos playas: la Praia de Baixo y la Praia de Cima, una frente a la otra.',
  ds_p3: 'La Pinheira ya no es solo un pueblo de pescadores de tradición azoriana: llegó el desarrollo, pero sigue la convivencia tranquila entre visitantes y vecinos, y los ranchos de pesca todavía marcan el paisaje.',
  ds_origem: 'El origen del nombre',
  ds_origem_txt: 'Cuentan que en la ensenada había árboles de madera liviana y resistente, muy usados para hacer boyas para las redes de pesca. El fruto se parecía a una piña; por eso los árboles se llamaban pinheiras, y la playa, que todavía no tenía nombre, quedó como la Pinheira.',
  ds_por_que: '¿Por qué elegir la Pinheira?',
  ds_motivo_1: 'Praia de Baixo: aguas calmas, ideal para familias',
  ds_motivo_2: 'Pesca artesanal y pescado fresco todos los días',
  ds_motivo_3: 'Atardeceres sobre el Pontão y las rocas',
  ds_motivo_4: 'Playas vecinas para todos los gustos: surf, buceo y senderos',
  ds_motivo_5: 'Comunidad acogedora y ambiente tranquilo para los chicos',
  ds_motivo_6: 'A 3 km de la famosa Guarda do Embaú',
  ds_atrativos_titulo: 'Atractivos y paseos',
  ds_atrativos_sub: 'La Ensenada da Pinheira tiene de todo: desde la playa desierta para surfistas hasta el paseo en barco en familia, a pocos minutos de los residenciales.',
  ds_mapa_enseada: 'Mapa de la Ensenada da Pinheira', ds_enseada: 'Ensenada da Pinheira — Palhoça, Santa Catarina', ds_destaque: 'destacado',
  ds_at_pontao: 'Pontão da Pinheira',
  ds_at_pontao_txt: 'Conjunto de rocas entre la playa y el acantilado, con piletas naturales que forma la marea. Ideal para bañarse, para la pesca artesanal y para ver el atardecer.',
  ds_at_baixo: 'Praia de Baixo',
  ds_at_baixo_txt: 'Playa de ensenada de 7 km, de aguas calmas y limpias. Perfecta para familias, caminatas y deportes náuticos, con pescado fresco de la pesca artesanal todos los días.',
  ds_at_urubu: 'Pedra do Urubu',
  ds_at_urubu_txt: 'Una de las vistas más lindas de Santa Catarina: desde arriba se ve la ensenada de la Pinheira, la Praia do Sonho, la Ponta dos Papagaios y la desembocadura del Rio da Madre. Vale cada paso de la subida.',
  ds_at_cima: 'Praia de Cima',
  ds_at_cima_txt: 'Aguas limpias y mucho movimiento en verano, con puesto de guardavidas, bares, tiendas y restaurantes.',
  ds_at_prainha: 'Prainha',
  ds_at_prainha_txt: 'Playa desierta con olas fuertes para surfistas. Mar agitado, pero de agua cristalina y paisaje salvaje.',
  ds_at_guarda: 'Guarda do Embaú',
  ds_at_guarda_txt: 'A 3 km de la Pinheira, en la desembocadura del Rio da Madre, con mar abierto y vista a la Ilha do Coral. Conocida en todo Brasil: un lugar de paz y belleza.',
  ds_at_maco: 'Praia do Maço',
  ds_at_maco_txt: 'Playa desierta de aguas limpias y olas fuertes, con acceso por tres senderos que salen del pie del morro de la Pinheira. Para quien busca naturaleza y tranquilidad.',
  ds_at_tabuleiro: 'Parque de la Serra do Tabuleiro',
  ds_at_tabuleiro_txt: 'Con guías, se pueden hacer senderos y ver animales y plantas nativos. Uno de los mayores parques de preservación continua de Brasil.',
  ds_chegar_titulo: 'Cómo llegar a la Pinheira',
  ds_aviao: 'En avión', ds_aviao_txt: 'Aeropuerto Internacional Hercílio Luz (Florianópolis), a 66 km (cerca de 1 hora en auto). Recomendamos alquilar un auto o contratar un traslado.',
  ds_carro: 'En auto', ds_carro_txt: 'BR-101 Sur hasta Palhoça y luego el acceso a la Praia da Pinheira. Estacionamiento con tasa obligatoria (1 cochera por departamento); cochera adicional con recargo.',
  ds_onibus: 'En micro', ds_onibus_txt: 'Terminal de Florianópolis → línea a Palhoça → combi o mototaxi hasta la Pinheira. Cerca de 1 h 30 en total.',
  ds_distancias: 'Distancias útiles', ds_distancias_txt: 'Centro de Florianópolis: 55 km · Palhoça (centro): 37 km · Guarda do Embaú: 3 km · Garopaba: 33 km · Imbituba: 53 km.',
  ds_rota: 'Ver ruta',

  'd:Térreo': 'Planta baja', 'd:1º Piso': '1.er piso', 'd:2º Piso': '2.º piso', 'd:Cobertura': 'Último piso',
  'd:Frente Mar': 'Frente al mar', 'd:Beira-mar': 'Junto al mar', 'd:A 50m da praia': 'A 50 m de la playa',
  'd:na Praia da Pinheira': 'en la Praia da Pinheira', 'd:a 50m da Praia da Pinheira': 'a 50 m de la Praia da Pinheira',
  'd:Casal': 'Matrimonial', 'd:Sofá Cama': 'Sofá cama', 'd:Solteiro': 'Individual',
  'd:Ar Condicionado': 'Aire acondicionado', 'd:Internet (Wi-Fi)': 'Internet (Wi-Fi)', 'd:TV': 'TV', 'd:Ducha': 'Ducha',
  'd:Cozinha': 'Cocina', 'd:Geladeira': 'Heladera', 'd:1 Quarto + Sofá Cama': '1 dormitorio + sofá cama', 'd:Fogão': 'Anafe',
  'd:Microondas': 'Microondas', 'd:Área com Churrasco': 'Área con parrilla',
};

const en = {
  noites: (n) => `${n} ${s(n, 'night', 'nights')}`,
  pessoas: (n) => `${n} ${s(n, 'guest', 'guests')}`,
  fim_de_semana: 'weekend',
  taxa_obrigatoria: 'Required', taxa_opcional: 'Optional',
  m_menos_pessoa: 'One guest fewer', m_mais_pessoa: 'One more guest',

  bk_titulo_resumo: 'Review your stay', bk_escolher_datas: 'Choose dates',
  bk_sem_datas: 'Choose check-in and check-out dates to see the price.',
  bk_continuar: 'Continue', bk_datas: 'Dates', bk_alterar: 'Change', bk_pessoas: 'Guests',
  bk_maximo: (n) => `up to ${n}`,
  bk_menos_pessoa: 'One guest fewer', bk_mais_pessoa: 'One more guest',
  bk_menos_pessoa_em: (a) => `One guest fewer in ${a}`, bk_mais_pessoa_em: (a) => `One more guest in ${a}`,
  bk_pessoas_por_apto: 'Guests per apartment',
  bk_total_combinado: 'Combined total', bk_total: 'Total price',
  bk_sinal_para_reservar: (p) => `Deposit to book (${p}%)`,
  bk_restante: 'Balance (at check-in)',
  bk_nada_cobrado: 'Nothing is charged until you confirm in the last step.',
  bk_titulo_extras: 'Extra services', bk_sub_extras: 'Add services to your stay (optional)',
  bk_por_reserva: 'per booking', bk_por_noite: 'per night', bk_por_hospede: 'per guest',
  bk_escopo_grupo: 'For the group (1×)', bk_escopo_apto: 'Per apartment (2×)',
  bk_menos_extra: (n) => `Decrease ${n}`, bk_mais_extra: (n) => `Increase ${n}`,
  bk_extras_total: 'Extras',
  bk_titulo_dados: 'Your details', bk_nome: 'Full name', bk_nome_ph: 'As on your ID',
  bk_email: 'Email', bk_telefone: 'Phone (WhatsApp)',
  bk_erro_nome: 'Please enter your full name.',
  bk_erro_email: 'Please check the email — it looks incomplete.',
  bk_erro_telefone: 'Please check the phone number, including the area code.',
  bk_privacidade: 'We use these details only for your booking: to send the confirmation and contact you about your stay.',
  bk_titulo_revisao: 'Review and confirm', bk_processando: 'Processing…', bk_confirmar: 'Confirm booking',
  bk_ocultar: 'Hide', bk_detalhes: 'Details',
  bk_sinal_agora: (p) => `Deposit due now (${p}%)`,
  bk_cancelamento_resumo: 'Conditions depend on how far ahead of check-in you cancel.',
  bk_ver_politica: 'See the full policy', bk_escolher_outras_datas: 'Choose other dates',
  bk_falar_whatsapp: 'Talk to us on WhatsApp',
  bk_duas_reservas: 'Two linked bookings will be made, under the same name and with a single payment.',
  bk_sinal_confirma: 'Paying the deposit confirms the booking.',

  err_indisponivel: 'Someone else just booked these dates. Please choose other dates.',
  err_preco_mudou: (e) => `The amounts were updated while you were booking: total ${money(e?.total)}, deposit ${money(e?.sinal)}. Please review and confirm again.`,
  err_muitas_pendentes: 'You already have bookings waiting for the deposit payment. Please complete those payments or contact us on WhatsApp.',
  err_minimo_noites: (e) => `The minimum stay for these dates is ${e?.min} nights.`,
  err_maximo_noites: (e) => `The maximum stay for these dates is ${e?.max} nights.`,
  err_capacidade: "The number of guests exceeds the apartment's capacity.",
  err_datas: "These dates can't be booked. Please choose other dates.",
  err_datas_fechadas: (e) => `Bookings for these dates aren't open yet (for now, until ${dataEm('en-US')(e?.ate)}).`,
  err_estadia_longa: (e) => `Online bookings are for stays of up to ${e?.max} nights. For longer stays, please contact us.`,
  err_generico: "We couldn't complete the booking right now. Please try again shortly or contact us on WhatsApp.",

  cf_titulo_falhou: 'Payment not completed', cf_titulo_paga: 'Booking confirmed',
  cf_titulo_aguardando: 'Payment being processed', cf_titulo_recebida: 'Booking received',
  cf_nova_pesquisa: 'New search',
  cf_generico: 'We received the payment response. The confirmation with all the details will arrive by email.',
  cf_generico_falhou: "The payment wasn't completed. If you like, message us on WhatsApp to try again or arrange another way to pay.",
  cf_seu_codigo: 'Your booking code', cf_apartamento: 'Apartment', cf_apartamentos: 'Apartments',
  cf_estadia: 'Stay', cf_hospede: 'Guest',
  cf_sinal_pago: (p) => `Deposit paid (${p}%)`, cf_sinal_a_pagar: (p) => `Deposit due (${p}%)`,
  cf_texto_falhou: "The deposit payment wasn't completed, so the booking isn't secured yet. Message us on WhatsApp to try again or arrange another way to pay.",
  cf_texto_pago: (e) => `Your apartment is booked. We've sent the details to ${e}. The balance is paid at check-in.`,
  cf_texto_aguardando: (e) => `We received your payment and are waiting for confirmation (Pix can take a few minutes). The details will go to ${e}.`,
  cf_texto_manual: (e) => `We received your booking. To secure it, the deposit is still due: we'll contact you on WhatsApp or by email (${e}) with the instructions.`,

  ps_favoritar: (n) => `Save ${n}`, ps_desfavoritar: (n) => `Remove ${n} from saved`,
  ps_indisponivel: 'Unavailable', ps_ver_datas_livres: 'See free dates',
  ps_ate_pessoas: (n) => `up to ${n} guests`,
  ps_combinar_obrigatorio: (h) => `Combine with another apartment — needed for ${h} guests`,
  ps_combinar: 'Can be combined with another apartment',
  ps_total: 'total', ps_taxas_incluidas: 'fees included', ps_datas_para_preco: 'Choose your dates to see the total price, fees included',
  ps_disp_no: (n) => `Availability at ${n} for these dates.`,
  ps_disp_nos: (k) => (k === 2 ? 'Availability at both residences for these dates.' : `Availability at the ${k} residences for these dates.`),
  ps_disp: 'Availability for these dates.',
  ps_n_de_m_disponiveis: (a, t) => `${a} of ${t} ${s(t, 'apartment', 'apartments')} available`,
  ps_n_apartamentos: (t) => `${t} ${s(t, 'apartment', 'apartments')}`,
  ps_n_casas: (t) => `${t} ${s(t, 'house', 'houses')}`,
  ps_n_aptos_casas: (a, c) => `${a} ${s(a, 'apartment', 'apartments')} and ${c} ${s(c, 'house', 'houses')}`,
  ps_n_de_m_disponiveis_curto: (a, t) => `${a} of ${t} available`,
  ps_combo_titulo: (h, n) => `For ${h} guests at ${n}, apartments need to be combined.`,
  ps_combo_sugestao: 'Suggestion:', ps_combo_capacidade: (c) => `total capacity of ${c} guests.`,
  ps_combo_tres: 'Online you can book up to 2 apartments together; for 3 or more, message us on WhatsApp.',
  ps_combo_sem: "There aren't enough free apartments at this residence for these dates.",
  ps_ver_apto: (n) => `See ${n}`,
  ps_selecionar_entrada: 'Choose check-in', ps_selecionar_saida: 'Choose check-out',
  ps_limpar_consulta: 'Clear search',
  ps_limpar_filtro: 'Clear filter', ps_filtros: 'Filters',
  ps_hero_local: 'Praia da Pinheira · Palhoça · Santa Catarina',
  ps_hero_titulo_1: 'Your summer home,', ps_hero_titulo_2: 'close to the sea.',
  ps_hero_texto: (n) => `Furnished, fully equipped apartments in ${n} Grupo PinheiraMar residences. Choose your dates and see what's free.`,
  ps_ver_apartamentos: 'See apartments', ps_ordenar: 'Sort by',
  ps_ordem_recomendados: 'Recommended', ps_ordem_menor: 'Price: low to high', ps_ordem_maior: 'Price: high to low',
  ps_essencia: 'Your summer home.', ps_horarios: 'Hours',
  ps_checkin_a_partir: (h) => `Check-in from ${h}`, ps_checkout_ate: (h) => `Check-out by ${h}`,
  ps_como_chegar: 'Getting here', ps_km_floripa: '55 km from Florianópolis', ps_km_aeroporto: '66 km from the airport',
  ps_datas_livres: (n) => `Free dates · ${n}`,
  ps_datas_livres_sub: 'Pick a free period to see this apartment in the results.',

  ap_voltar: 'Back', ap_link_copiado: 'Link copied', ap_compartilhar: 'Share', ap_salvar: 'Save', ap_salvo: 'Saved',
  ap_resumo: (cap, q, c) => `Up to ${cap} guests · ${q} ${s(q, 'bedroom', 'bedrooms')} · ${c} ${s(c, 'bed', 'beds')}`,
  ap_ver_avaliacoes: 'See reviews on Google', ap_avaliacoes_google: (n) => `${n} Google reviews`, ap_n_avaliacoes: (n) => `${n} reviews`,
  ap_frente_mar: 'Oceanfront', ap_foto_n: (i, n) => `${n} — photo ${i}`, ap_ver_todas_fotos: (n) => `See all ${n} photos`,
  ap_fechar: 'Close', ap_foto_anterior: 'Previous photo', ap_proxima_foto: 'Next photo',
  ap_pontos_fortes: 'Highlights',
  ap_hl_wifi: 'Free Wi-Fi', ap_hl_estacionamento: 'Parking', ap_hl_vista_mar: 'Sea view', ap_hl_churrasqueira: 'Barbecue grill',
  ap_hl_ar: 'Air conditioning', ap_hl_cozinha: 'Equipped kitchen', ap_hl_piscina: 'Pool', ap_hl_varanda: 'Balcony',
  ap_sobre: 'About the apartment', ap_acomodacoes: 'Where you’ll sleep', ap_comodidades: 'Amenities', ap_capacidade: 'Capacity',
  ap_capacidade_maxima: 'maximum capacity', ap_quartos: (n) => `${n} ${s(n, 'bedroom', 'bedrooms')}`, ap_para_dormir: 'to sleep in', ap_area: 'apartment size',
  ap_regras: 'House rules',
  ap_regra_checkin: 'Check-in', ap_regra_checkin_txt: (h) => `From ${h}`,
  ap_regra_checkout: 'Check-out', ap_regra_checkout_txt: (h) => `By ${h}`,
  ap_regra_silencio: 'Quiet hours', ap_regra_silencio_txt: "So everyone can rest, quiet hours are 10 pm to 7 am (except New Year's Eve and Carnival).",
  ap_regra_pets: 'Pets', ap_regra_pets_txt: (p) => `Welcome, with a one-time fee of ${p} per pet (up to 10 kg, max. 2).`,
  ap_regra_pets_consulte: 'Please ask us before bringing pets.',
  ap_regra_estacionamento: 'Parking', ap_regra_vaga_obrig: 'Garage space with a mandatory one-time fee.',
  ap_regra_vaga: 'Please ask about parking availability.', ap_regra_vaga_extra: (p) => `Extra space: ${p} (subject to availability).`,
  ap_regra_fumar: 'Smoking', ap_regra_fumar_txt: 'Smoking is not allowed indoors or in shared areas.',
  ap_localizacao: 'Location', ap_mapa: 'Map', ap_comercio: 'A few steps from local shops: supermarkets, bars and restaurants.',
  ap_datas_e_reserva: 'Dates and booking', ap_sem_datas: 'No dates', ap_limpar_pesquisa: 'Clear search',
  ap_checkin: 'Check-in', ap_checkout: 'Check-out', ap_adicionar_data: 'Add date', ap_hospedes: 'Guests',
  ap_precisa_segundo: (h, cap) => `You searched for ${h} guests and this apartment sleeps up to ${cap}. Tick "Add a second apartment" below to book for the whole group.`,
  ap_segundo_apto: 'Add a second apartment', ap_segundo_apto_sub: 'Joint booking · same name · one payment',
  ap_escolha_segundo: '— Choose the 2nd apartment —', ap_indisponivel_curto: 'unavailable', ap_pessoas_em: (n) => `Guests in ${n}`,
  ap_minimo_noites: (n, t) => `For these dates${t ? ` (${t})` : ''}, the minimum stay is ${n} nights.`,
  ap_maximo_noites: (n, t) => `For these dates${t ? ` (${t})` : ''}, the maximum stay is ${n} nights.`,
  ap_disponivel: 'Available', ap_indisponivel_datas: 'Unavailable for these dates', ap_sinal: (p) => `Deposit (${p}%)`,
  ap_btn_selecione_datas: 'Choose dates', ap_btn_indisponivel: 'Unavailable',
  ap_btn_minimo: (n) => `Minimum ${n} nights`, ap_btn_maximo: (n) => `Maximum ${n} nights`,
  ap_btn_adicione_segundo: 'Add the 2nd apartment', ap_btn_escolha_segundo: 'Choose the 2nd apartment',
  ap_btn_segundo_indisponivel: (n) => `${n} unavailable`, ap_btn_capacidade: (h) => `Not enough room for ${h} guests`,
  ap_btn_reservar: 'Book now', ap_sem_cobrancas: (p) => `Nothing is charged until you confirm · ${p}% deposit to book`,
  ap_precisa_ajuda: 'Need help?', ap_fale_whatsapp: 'Message us on WhatsApp',
  ap_ver_detalhes_preco: 'See price details', ap_reservar_curto: 'Book', ap_ocupado_datas: 'Booked on these dates',
  ap_mudar_datas: 'Change dates', ap_falta_detalhe: 'One more detail to book',
  ap_adicione_datas_preco: 'Add your dates to see the price for your stay', ap_escolher_datas: 'Choose dates',

  cal_mes_anterior: 'Previous month', cal_proximo_mes: 'Next month',
  cal_escolha_saida: 'Choose check-out date', cal_escolha_entrada: 'Choose check-in date',
  cal_ocupado: 'booked', cal_fechado: 'not open for booking yet', cal_abertas_ate: (d) => `Bookings open until ${d}.`,
  cal_desmarcar: 'Clear dates', cal_legenda_livre: 'free', cal_legenda_ocupado: 'booked',

  ds_tab_pinheira: 'Pinheira', ds_tab_atrativos: 'Things to do', ds_tab_chegar: 'Getting here',
  ds_titulo: 'Discover Pinheira',
  ds_sub: 'One of the most sought-after beaches near Florianópolis: Azorean heritage, natural pools and the best of the Santa Catarina coast.',
  ds_viva: 'The place is part of the holiday',
  ds_p1: 'Praia da Pinheira is one of the busiest beaches in Greater Florianópolis, welcoming visitors from all over Brazil and abroad.',
  ds_p2: 'It sits in a bay 37 km from the centre of Palhoça and 55 km from central Florianópolis, and is split into two beaches — Praia de Baixo and Praia de Cima — facing each other.',
  ds_p3: 'Pinheira is no longer just a fishing village of Azorean tradition: development has arrived, but the easy-going mix of visitors and locals remains, and the fishermen’s huts still shape the landscape.',
  ds_origem: 'Where the name comes from',
  ds_origem_txt: 'The story goes that the bay was covered in trees with light, sturdy wood, used to make floats for fishing nets. Their fruit looked like a pine cone — so the trees were called pinheiras, and the beach, which had no name yet, became Pinheira.',
  ds_por_que: 'Why choose Pinheira?',
  ds_motivo_1: 'Praia de Baixo: calm water, great for families',
  ds_motivo_2: 'Traditional fishing and fresh fish every day',
  ds_motivo_3: 'Sunsets over the Pontão and the rocks',
  ds_motivo_4: 'Nearby beaches for every taste — surfing, diving and trails',
  ds_motivo_5: 'A welcoming community and a relaxed place for children',
  ds_motivo_6: '3 km from the famous Guarda do Embaú',
  ds_atrativos_titulo: 'Things to see and do',
  ds_atrativos_sub: 'The Pinheira bay has it all — from deserted surf beaches to family boat trips, just minutes from the residences.',
  ds_mapa_enseada: 'Map of the Pinheira bay', ds_enseada: 'Enseada da Pinheira — Palhoça, Santa Catarina', ds_destaque: 'highlight',
  ds_at_pontao: 'Pontão da Pinheira',
  ds_at_pontao_txt: 'A group of rocks between the beach and the headland, with natural pools formed by the tides. Great for a swim, traditional fishing and watching the sunset.',
  ds_at_baixo: 'Praia de Baixo',
  ds_at_baixo_txt: 'A 7 km bay beach with calm, clear water. Perfect for families, walks and water sports — with fresh fish from local fishermen every day.',
  ds_at_urubu: 'Pedra do Urubu',
  ds_at_urubu_txt: 'One of the finest views in Santa Catarina: from the top you can see the Pinheira bay, Praia do Sonho, Ponta dos Papagaios and the mouth of the Rio da Madre. Worth every step of the climb.',
  ds_at_cima: 'Praia de Cima',
  ds_at_cima_txt: 'Clean water and a lively summer scene, with a lifeguard post, bars, shops and restaurants.',
  ds_at_prainha: 'Prainha',
  ds_at_prainha_txt: 'A deserted beach with strong waves for surfers. Rough sea, but crystal-clear water and wild scenery.',
  ds_at_guarda: 'Guarda do Embaú',
  ds_at_guarda_txt: '3 km from Pinheira, at the mouth of the Rio da Madre, with open sea and a view of Ilha do Coral. Known all over Brazil — a place of peace and beauty.',
  ds_at_maco: 'Praia do Maço',
  ds_at_maco_txt: 'A deserted beach with clean water and strong waves, reached by three trails from the foot of Pinheira hill. For those after nature and quiet.',
  ds_at_tabuleiro: 'Serra do Tabuleiro Park',
  ds_at_tabuleiro_txt: 'With a guide you can hike trails and spot native wildlife and plants. One of the largest continuous conservation parks in Brazil.',
  ds_chegar_titulo: 'Getting to Pinheira',
  ds_aviao: 'By plane', ds_aviao_txt: 'Hercílio Luz International Airport (Florianópolis), 66 km away (about an hour by car). We recommend renting a car or booking a transfer.',
  ds_carro: 'By car', ds_carro_txt: 'BR-101 south to Palhoça, then the road to Praia da Pinheira. Parking with a mandatory fee (1 space per apartment); extra spaces at an additional cost.',
  ds_onibus: 'By bus', ds_onibus_txt: 'Florianópolis bus station → bus to Palhoça → van or motorbike taxi to Pinheira. About 1 h 30 in total.',
  ds_distancias: 'Useful distances', ds_distancias_txt: 'Florianópolis centre: 55 km · Palhoça (centre): 37 km · Guarda do Embaú: 3 km · Garopaba: 33 km · Imbituba: 53 km.',
  ds_rota: 'Get directions',

  'd:Térreo': 'Ground floor', 'd:1º Piso': 'First floor', 'd:2º Piso': 'Second floor', 'd:Cobertura': 'Top floor',
  'd:Frente Mar': 'Oceanfront', 'd:Beira-mar': 'By the sea', 'd:A 50m da praia': '50 m from the beach',
  'd:na Praia da Pinheira': 'at Praia da Pinheira', 'd:a 50m da Praia da Pinheira': '50 m from Praia da Pinheira',
  'd:Casal': 'Double', 'd:Sofá Cama': 'Sofa bed', 'd:Solteiro': 'Single',
  'd:Ar Condicionado': 'Air conditioning', 'd:Internet (Wi-Fi)': 'Internet (Wi-Fi)', 'd:TV': 'TV', 'd:Ducha': 'Shower',
  'd:Cozinha': 'Kitchen', 'd:Geladeira': 'Fridge', 'd:1 Quarto + Sofá Cama': '1 bedroom + sofa bed', 'd:Fogão': 'Stove',
  'd:Microondas': 'Microwave', 'd:Área com Churrasco': 'Barbecue area',
};

export const TEXTOS = { pt, es, en };
